tasks = [
    {
        "name": "Complete Report",
        "description": "Finish writing the quarterly report",
        "due_date": "2023-11-20T12:00:00Z",
        "status": "Done",
        "creator": 4,
    },
    {
        "name": "Meeting Prep",
        "description": "Prepare presentation slides for the team meeting",
        "due_date": "2023-11-22T09:30:00Z",
        "status": "In progress",
        "creator": 2,
    },
    {
        "name": "Email Follow-ups",
        "description": "Follow up on pending emails and respond to queries",
        "due_date": "2023-11-25T16:00:00Z",
        "status": "Not done",
        "creator": 6,
    },
    {
        "name": "Code Review",
        "description": "Review pull requests and provide feedback",
        "due_date": "2023-11-28T14:00:00Z",
        "status": "Done",
        "creator": 3,
    },
    {
        "name": "Project Evaluation",
        "description": "Evaluate project progress and update status report",
        "due_date": "2023-12-01T10:00:00Z",
        "status": "In progress",
        "creator": 5,
    },
    {
        "name": "Data Analysis",
        "description": "Analyze collected data and generate insights",
        "due_date": "2023-12-05T11:30:00Z",
        "status": "Not done",
        "creator": 1,
    },
    {
        "name": "Client Presentation",
        "description": "Prepare presentation for client meeting",
        "due_date": "2023-12-08T15:00:00Z",
        "status": "Done",
        "creator": 4,
    },
    {
        "name": "Bug Fixing",
        "description": "Fix reported bugs in the application",
        "due_date": "2023-12-10T13:45:00Z",
        "status": "In progress",
        "creator": 2,
    },
    {
        "name": "Content Creation",
        "description": "Create new content for marketing campaign",
        "due_date": "2023-12-12T10:00:00Z",
        "status": "Done",
        "creator": 6,
    },
    {
        "name": "Training Session",
        "description": "Prepare training materials for upcoming session",
        "due_date": "2023-12-15T09:00:00Z",
        "status": "Not done",
        "creator": 3,
    },
    {
        "name": "Budget Planning",
        "description": "Review and plan budget for next quarter",
        "due_date": "2023-12-18T14:30:00Z",
        "status": "In progress",
        "creator": 5,
    },
    {
        "name": "Documentation Update",
        "description": "Update project documentation with recent changes",
        "due_date": "2023-12-20T11:00:00Z",
        "status": "Done",
        "creator": 1,
    },
    {
        "name": "Team Building Activity",
        "description": "Organize team-building activity for department",
        "due_date": "2023-12-23T16:45:00Z",
        "status": "In progress",
        "creator": 4,
    },
    {
        "name": "Content Review",
        "description": "Review and edit content for publication",
        "due_date": "2023-12-25T10:30:00Z",
        "status": "Not done",
        "creator": 6,
    },
    {
        "name": "System Maintenance",
        "description": "Perform routine maintenance tasks on the system",
        "due_date": "2023-12-28T09:00:00Z",
        "status": "Done",
        "creator": 2,
    },
    {
        "name": "Client Feedback Analysis",
        "description": "Analyze client feedback for improvement",
        "due_date": "2023-12-30T13:00:00Z",
        "status": "In progress",
        "creator": 3,
    },
    {
        "name": "Project Planning",
        "description": "Initiate planning for new project phase",
        "due_date": "2024-01-02T14:15:00Z",
        "status": "Not done",
        "creator": 5,
    },
    {
        "name": "Presentation Practice",
        "description": "Practice presentation for upcoming event",
        "due_date": "2024-01-05T16:30:00Z",
        "status": "Done",
        "creator": 1,
    },
    {
        "name": "Research Task",
        "description": "Conduct research on market trends",
        "due_date": "2024-01-08T12:00:00Z",
        "status": "In progress",
        "creator": 4,
    },
    {
        "name": "Task Prioritization",
        "description": "Reevaluate task priorities for better efficiency",
        "due_date": "2024-01-10T11:30:00Z",
        "status": "Not done",
        "creator": 6,
    },
]
